### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by goldami1** [goldami1/FinalYearProject#21]
Update color for login button for iOS
Add spacing for notifications bar on iOS

**Comment by gil-ronen** [comment]
@goldami1  The spacing on the upper margin should be **30** and **NOT** 20.
Also on the login page and the loading page there is no need for spacing on the upper margin (notifications bar).
I fixed that.
**Please update color for login button for iOS - not blue.**

**Comment by goldami1** [comment]
@gil-ronen Fixed mentioned above.
