### ISSUE TITLE
Deployment of application

### ISSUE THREAD

**Issue by goldami1** [goldami1/FinalYearProject#22]
Deployment of application to iPhone prior meeting on 03/05.

**Comment by goldami1** [comment]
After discussion, by @gil-ronen - implementation would be done by the following meeting (on 03/05)

**Comment by gil-ronen** [comment]
Done!
In the meantime, I'm using free provisioning to deploy the Xamarin.iOS application to the iOS device without being part of any Apple Developer Program.
The Provisioning Profiles created in this way will expire after one week (untill 05/05/2018).
